### ISSUE TITLE
Dependency-check v9.0.0

### ISSUE THREAD

**Issue by bjansen** [dependency-check/Dependency-Check_Action#28]
Hi,

Sorry if this is the wrong place to ask this question. Would it be possible to push a new version of `owasp/dependency-check-action` on docker hub that uses dependency-check v9.0.0? We're using your docker image to speed up our CI builds, and they are currently failing because we're using the latest version of the dependency-check maven plugin against an older format of the database.

Thanks.

**Comment by javixeneize** [comment]
Thats interesting... the builder is here - https://github.com/dependency-check/DependencyCheck_Builder/blob/main/Dockerfile, and it has failed for the last two days

When was dependency check 9.0.0 released? @jeremylong

**Comment by jmtt89** [comment]
Hi, Dependency Check version 9.0.0 was released the Nov 22 and include Braking changes...  https://github.com/jeremylong/DependencyCheck#900-upgrade-notice  

The problem is because https://nvd.nist.gov/ deprecated the RSS (it will stop working on December 15, 2023) and they want all of us to use API to fetch the vulnerabilities... And the API provided by NVD is rate limited....

NVD API 2.0 Rate Limit (ref. https://nvd.nist.gov/developers/start-here) 

Rate limit without an API key: 5 requests in a rolling 30-second window.
Rate limit with an API key: 50 requests in a rolling 30-second window.

**Comment by scottkennedy** [comment]
It would be great if this could be brought up to date.  It's only flagging 2 issues on my codebase, whereas 9.0.7 is flagging 7.

**Comment by jeremylong** [comment]
I had pinned this to 8.4.3 due to issues with 9.0.x and the NVD API. The builder was updated 2 days ago to use the latest again: https://github.com/dependency-check/DependencyCheck_Builder/commit/7bbd5e4d8b65a6b9b8fc22d7b2fb042b580bcf23
